### ISSUE TITLE
[Meta] Teams Overhaul

### ISSUE THREAD

**Issue by sigrunixia** [obsidianmd/obsidian-help#692]
## Purpose

The goal of this issue to is create a section of the help docs that is oriented towards Teams and how they use Obsidian. It is considered a one stop shop, to shorten the amount of search and navigation needed on the site.

Many of the items on these page will be soft-embedded versions of content on other pages. 

However others, such as commercial license page, will be moved and expanded to accommodate very common questions.

## Scope

English Help Docs, with a new master section, and gentle refactoring of existing sections to help augment this new master section. 

## Goals

- Reduce support box general questions
	- Add link to teams section to auto reply
- Allow moderators and staff to have quick references to provide on discord/forums

## Tasks

- [x] Obsidian Sync section refactor
- [x] Obsidian Publish section refactor
- [x] Create Teams Section (Names below are not final)
	- [x] Commercial Licenses
	- [x] Installing/Updating Obsidian
	- [x] Securing Obsidian
	- [ ] Sync for Teams
	- [ ] Publish for Teams
- [x] Adjust existing payment section
	- [x] Add section on purchasing services
	- [x] Add section on recovering your own invoice
		- [x] Add section on editing your invoice

**Comment by sigrunixia** [comment]
## Commercial license questions to address

**Comment by sigrunixia** [comment]
## Installation questions to address

1. Can you deploy Obsidian with the license key included?
